### ISSUE TITLE
Option to keep Exif data

### ISSUE THREAD

**Issue by eclair4151** [igreenwood/SimpleCropView#63]
Currently when you crop a photo all the exif data from the original photo gets nuked. There should be  a way to keep the exif data from the original photo so the gps data and time stamp dont get deleted

**Comment by Nuclominus** [comment]
@eclair4151I think this problem is not in CropImageView. It's a common problem on android 7 - after edit image exif was lost. But you may fast fix it - copy exif attributes from source to target cropped image.
